name: CD workflow 1.0.6

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: CHECK ROOT PATH
        run: ls -a
      - name: DOCKER VERSION CHECK
        run: docker --version
      # TODO
